# Generated by Django 5.0.1 on 2024-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rec_product', verbose_name='фото продукта')),
                ('disc', models.TextField(verbose_name='описание')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Рекамендованая Продукт',
                'verbose_name_plural': 'Рекамендованые Продукты',
            },
        ),
    ]
