# Generated by Django 5.0.1 on 2024-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_milkshake_options_fructjuice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fructjuice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='icecreame',
            name='category',
        ),
        migrations.RemoveField(
            model_name='milkshake',
            name='category',
        ),
        migrations.AlterField(
            model_name='fructjuice',
            name='image',
            field=models.ImageField(upload_to='fruct_juice/', verbose_name='Фото'),
        ),
    ]
