# Generated by Django 5.0.1 on 2024-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_fructjuice_category_remove_icecreame_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='price_change/', verbose_name='фото')),
                ('disc', models.TextField(verbose_name='описание')),
                ('new_price', models.CharField(max_length=255, verbose_name='новая цена')),
                ('old_price', models.CharField(max_length=255, verbose_name='старая цена')),
            ],
            options={
                'verbose_name': 'Обнавление цен',
                'verbose_name_plural': 'Обнавление цен',
            },
        ),
    ]
