# Generated by Django 5.0.1 on 2024-01-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='fructjuice',
            name='disc',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreame',
            name='disc',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkshake',
            name='disc',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
