# Generated by Django 5.0.1 on 2024-01-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cake_fruitmilkshake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FruitMilkshake',
        ),
    ]
