# Generated by Django 5.0.1 on 2024-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cake_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='baking', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Выпычка',
                'verbose_name_plural': 'Выпычка',
            },
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
    ]
