# Generated by Django 5.0.1 on 2024-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone', models.CharField(max_length=255, verbose_name='номер')),
                ('person', models.CharField(max_length=255, verbose_name='количесва людей')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.CharField(max_length=255, verbose_name='время')),
                ('massege', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
