# Generated by Django 5.0.1 on 2024-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_massege_reservation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('subject', models.CharField(max_length=255, verbose_name='обьект')),
                ('message', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
