# Generated by Django 5.0.1 on 2024-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog', verbose_name='фото')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('disc', models.TextField(verbose_name='описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
