# Generated by Django 5.0.1 on 2024-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment', verbose_name='фото')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('prof', models.CharField(max_length=255, verbose_name='професия')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': ('Коммент',),
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
