# Generated by Django 5.0.1 on 2024-01-05 18:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(upload_to='logo', verbose_name='Название сайта')),
                ('image', models.ImageField(upload_to='fons', verbose_name='фон')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image2', models.ImageField(upload_to='disc_image', verbose_name='фото')),
                ('instagram', models.URLField(verbose_name='Истаграмм url')),
                ('dribble', models.URLField(verbose_name='Dribbble url')),
                ('twitter', models.URLField(verbose_name='твиттер url')),
                ('youtube', models.URLField(verbose_name='ютуб url')),
                ('addres', models.CharField(max_length=255, verbose_name='адрес')),
                ('gmail', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Оснавные настройки',
                'verbose_name_plural': 'Оснавные настройки',
            },
        ),
    ]
