# Generated by Django 5.0.1 on 2024-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='image_title',
            field=models.ImageField(upload_to='logo', verbose_name='логотип'),
        ),
    ]
