# Generated by Django 5.0.1 on 2024-01-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients', verbose_name='фото клиента')),
                ('name', models.CharField(max_length=255, verbose_name='имя клиента')),
                ('prof', models.CharField(max_length=255, verbose_name='професия клиента')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзавы',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='fons',
            field=models.ImageField(default=1, upload_to='fonss', verbose_name='фон2'),
            preserve_default=False,
        ),
    ]
