# Generated by Django 5.0.1 on 2024-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clients_settings_fons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('disc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Частый задаваеммый вопрос',
                'verbose_name_plural': 'Частые задаваеммые вопрос',
            },
        ),
    ]
